sudo: required

language: generic

service:
  - docker

before_install:
  - docker build -t utkarsh19/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true utkarsh19/react-test npm test

after_success:
  - docker build -t utkarsh19/multi-client ./client
  - docker build -t utkarsh19/multi-server ./server
  - docker build -t utkarsh19/multi-nginx ./nginx
  - docker build -t utkarsh19/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker push utkarsh19/multi-client:latest
  - docker push utkarsh19/multi-server:latest
  - docker push utkarsh19/multi-nginx:latest
  - docker push utkarsh19/multi-worker:latest
  

